[build]
  command = "curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v1.6.39/quarto-1.6.39-linux-amd64.tar.gz -o quarto.tar.gz && tar -xzf quarto.tar.gz && ./quarto-1.6.39-linux-amd64/bin/quarto render"
  publish = "_site"
